export { default as clock } from './clock.svg';
export { default as cross } from './cross.svg';
export { default as gear } from './gear.svg';
export { default as list } from './list.svg';
export { default as plus } from './plus.svg';
export { default as trash } from './trash.svg';
export { default as trashRed } from './trashRed.svg';
export { default as angleRight } from './angleRight.svg';
export { default as arrowLeft } from './arrowLeft.svg';
